config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :avoirs

  map.resources :groupapps, :has_many=>[:applications, :roles]

  map.resources :presentations

  map.resources :fichiercompressions, :collection => {:getversion => :get, :remplacement_shapes => :get, :supnameshapes => :get, :addnameshapes => :get, :sortable_marques_topics => :get, :sortable_marques_topics_javascript => :get, :sortable_logos_blocks_javascript => :get, :set_position_logos => :get, :set_position_logos_circle_red => :get, :suplogosplans => :get, :set_position_logos_remplacement => :get, :version_file => :get, :set_version_apps => :get, :filepdfimg => :get, :detailimgpdf => :get, :getcurrentversion => :get, :test_envoie_file_local_ftp => :get, :affichage_svg => :get}, :has_many=>:avoirs

  map.resources :pings, :member => { :validate => :get }, :collection => {:create => :get}

  map.resources :applications, :collection => {:edit_client => :get, :edit_etat => :get, :valid_edit_etat => :get, :valid_edit_client => :get, :search_auto_completion => :get, :get_sha => :get, :get_statpaiement => :get, :apps_sharing_zips => :get, :get_command => :get, :set_command => :get, :set_old_serial_apps => :get, :get_remotename => :get, :set_remotename => :get, :get_all_apps_fichiercompressions => :get, :getappgroup => :get}, :has_one=>[:groupapps], :has_many=>[:users, :avoirs]

  map.resources :controllersdroits

  map.resouces "addrolessimplifie", :controller=>:roles, :action=>"new"
  map.resouces "newpdfreader", :controller=>:fichiercompressions, :action=>"new"
 
  map.resources :roles, :has_many=>[:users, :controllersdroits, :groupapps]

  map.root :controller=> "user_sessions", :action=>"new"
  map.login "login", :controller=>"user_sessions", :action=>"new"
  map.logout "logout", :controller=>"user_sessions", :action=>"destroy"
  map.resources :user_sessions

  map.resources :users, :has_many=>:applications, :collection => {:search_user_auto_completion => :get, :valid_search_user => :post}
  map.resources :javascript, :collection => {:addnamestranslations => :get, :popup_logos_for_mark => :get, :add_block => :get, :see_all_topics_blocks => :get, :sortable_logos_blocks_javascript => :get, :add_logos => :get, :updatelogos => :get, :liste_applications_groupapps => :get, :detail_apps => :get, :tableau_recapitulatif_fichiercompressions => :get, :tab_select_apps => :get, :tableau_recapitulatif_all_apps => :get, :apps_javascript_periodicalupdater => :post, :message_popup_affichage => :get, :show_get_name_value => :get, :search_bornes => :get, :add_new_groupapps => :get, :valid_add_new_groupapps => :get, :check_number_apps => :get, :get_info_fichiercompressions => :get, :file_liste_all_apps => :get, :get_groupapp_name => :get, :snatch_close_window => :post}
  map.resources :connect
  map.resources :statistics, :collection => {:new => :post, :create => :post, :visugraph => :get, :menu => :get, :edit_colonne_table => :get, :comparaisonstat => :get, :categoriecolonne => :get, :newcategoriecolonnetables => :get, :assoc_colonne_table => :get, :update_colonne_table => :get, :statistiquesprincipal => :get, :statistiquesprincipalindex => :get, :testcopiestat => :get }

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/groupapp.rb
class Groupapp < ActiveRecord::Base
	validates_presence_of :name, :message => "Veuillez entrer le nom du Groupe d'applications que vous désireé ajouter"
	has_many :applications
	has_and_belongs_to_many :roles
	validates_uniqueness_of :name
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ByPage
	CONF_PATH = "#{RAILS_ROOT}/config/conf_page.yml"
	def initialize(controller)
                @controller = controller
		@chargementpage = YAML::load_file(CONF_PATH)	
	end

	def page
		@chargementpage[@controller]
	end
end

class Langue
	attr_accessor :langue
end

class SessionFileDB
	attr_accessor :filedb
end

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
  helper_method :current_user
  before_filter :set_user_language

  [:notice, :error].each do |flash_type|
    define_method("flash_#{flash_type}") do |text|
      _flash(flash_type, text)
    end

    define_method("t_flash_#{flash_type}") do |*args|
      _flash(flash_type, t(*args))
    end

    define_method("auto_flash_#{flash_type}") do |*args|
      auto_flash(flash_type, *args)
    end
  end

  def auto_flash(status, interpolation_hash = {}, options = {})
    action = options.delete(:action) || action_name.to_s + (action_name.to_s[-1,1] == 'e' ? "d" : "ed")
    model_class = options.delete(:object) || controller_name.to_s
    notice_text = t("flashs.#{model_class.singularize}.#{action}#{"_failed" if status.to_sym == :error}", interpolation_hash)
    _flash(status.to_sym, notice_text)
  end

  def magic_flash(status, interpolation_hash = {}, options = {})
    send("auto_flash_#{status == true ? 'notice' : 'error'}".to_sym, interpolation_hash, options)
    return status
  end

  def verifier_acces_admin
	if current_user
		unless current_user.role_id == 1
			flash[:notice] = t("controller.notice.application.verifier_acces_admin") 
			redirect_to edit_user_path(current_user.id)  
		end
        else	
	   flash[:notice] = t("controller.notice.application.not_acces")
  	   redirect_to login_path
	end
  end
 
  def verifier_acces
        unless current_user
	   flash[:notice] = t("controller.notice.application.not_acces")
  	   redirect_to login_path
        end
  end

  def verif_acces_controller_page(controller_name,actioname)
	 verif_acces_controller_page =  Controllersdroit.find(:first, :joins=>[:roles], :conditions=>"controllersdroits.name='#{controller_name}/#{actioname}' and roles.id=#{current_user.role_id.to_i}")
 		Rails.logger.info "-=-=-=-=--=-=-#{verif_acces_controller_page.nil? ? true : false}-=-=-=-=-"
		verif_acces_controller_page.nil? ? true : false
  end

  def verif_acces_user_controller
	if current_user
		unless control_acces_user_controller(controller_name,action_name)
			flash[:notice] = t("controller.notice.application.verifier_acces_admin") 
			redirect_to edit_user_path(current_user.id)
		else
			if verif_acces_controller_page(controller_name,action_name) == false
				redirect_to edit_user_path(current_user.id)
			end
		end
	else
	   flash[:notice] = t("controller.notice.application.not_acces")
  	   redirect_to login_path
	end
  end

  def control_acces_user_controller(controllername,actioname)
	verif_droit_controller = Controllersdroit.find :first, :joins=>[:roles], :conditions=>"controllersdroits.name='#{controllername.to_s}' and controllersdroits.name<>'#{controllername.to_s}/#{actioname.to_s}' and roles.id=#{current_user.role_id.to_i}"
	unless verif_droit_controller.nil?
		verif_acces_controller_page(controllername,actioname)		
	else
		false
	end
	#verif_droit_controller.nil? ? false : true
  end

  private
  def _flash(status, text)
    flash[status] = text.to_s
  end

  def current_user_session
        return @current_user_session if defined?(@current_user_session)
        @current_user_session = UserSession.find
  end

  def current_user
        return @current_user if defined?(@current_user)
        @current_user = current_user_session && current_user_session.record
  end

  def set_user_language
                      unless session['langue'].nil?
			p = session['langue']
  			I18n.locale = p.langue
                      else
				I18n.locale = current_user.language if current_user
		      end
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templa
# tes in the application.
module ApplicationHelper	
	def file_write(file_bin,url,type_ecriture)
     		 if File.open(url, type_ecriture) do |f|
	   		f.write file_bin
         	end
      		else
		Rails.logger.info "test erreur_=_=_=_=_=_=_=_=_="
      		end
      		url
  	end

	def tab_td_style(indice)
		indice == 0 ? "white" : "#e5e5e5"
	end

	def get_url_home(controller_name,action_name,request_uri)
	   result_link = "#{get_link_home(controller_name)}"
           unless request_uri.scan(/^\/.{1,}\?(.{1,})$/).empty? 
		params = request_uri.scan(/^\/.{1,}\?(.{1,})$/)[0][0].to_s
	       
		case controller_name
			when "applications"
				result_link += "#{link_to get_controller_language(controller_name), :controller=>controller_name}/#{set_params_for_link(params)}"
			when "fichiercompressions"
				result_link += "#{link_to t("applications.applications_url"), applications_url}/#{get_controller_language(controller_name)}/#{set_params_for_link_fichiercompressions(params)}"
			when "statistics"
				result_link += "#{get_url_statistics(action_name,request_uri,params)}"
		end
	   else
		id = request_uri.scan(/^\/.{1,}\/(.{1,})\/.{1,}$/).to_s.to_i
	        	unless action_name.nil?
				case action_name
				      when "edit"
				      	result_link += "#{link_to get_controller_language(controller_name), :controller=>controller_name}/#{get_info_url_edit(controller_name,id)}"
			  	      when "index"
					result_link += "#{get_controller_language(controller_name)}"
			      				      
				end
			end
	   end
	   result_link
	end

	private
	def set_params_for_link_fichiercompressions(params)
		detail_params = params.scan(/^(.{1,})=(.{1,})$/)[0]

		case detail_params[0]
			when "id"
			       get_info_url_edit("applications",detail_params[1])	
		end
	end

	def get_role_id(role_id)
		role = Role.find(role_id)
		link_to role.name, :controller=>"statistics", :action=>"index", :role_id=>role.id
	end

	def get_role_application_id(application_id)
		application = Application.find(application_id.to_i)
		link_to application.role.name, :controller=>"statistics", :action=>"index", :role_id=>application.role_id
	end
	
	def get_url_statistics(action_name,request_uri,params)
		#params
		#params.empty? ? t("statistics.statistics_url") : 	
		case action_name
			when "show"			
				 "#{link_to t("statistics.statistics_url"), :controller=>"statistics", :action=>"index"}/#{params.split("=")[0].to_s == "role_id" ? get_role_id(params.split("=")[1].to_i) : get_role_application_id(params.split("=")[1].to_i)}/#{request_uri.scan(/^\/.{1,}\/(.{1,})\?.{1,}$/)[0][0]}"		
			when "index"
				params.empty? ? t("statistics.statistics_url") : "#{link_to(t("statistics.statistics_url"), :controller=>"statistics", :action=>"index")}/#{params.split("=")[0].to_s == "role_id" ? get_role_id(params.split("=")[1].to_i) : get_role_application_id(params.split("=")[1].to_i)}"
		end
	end

	def get_info_url_edit(controller,id)
		case controller
			when "applications"
				Application.find(id).name
			when "roles"	
				Role.find(id).name
			when "users"
				User.find(id).username
			when "fichiercompressions"
				id
			when "groupapps"
				Groupapp.find(id).name
			when "controllersdroits"
				Controllersdroit.find(id).name
		end
	end

        def get_controller_language(controller)
		case controller
			when "applications"
				t("applications.applications_url")
		        when "users"
				t("user.user_url")
			when "fichiercompressions"
				t("fichiercompressions.fichiercompressions_url")
			when "presentations"
				t("presentations.presentations_url")
			when "roles"
				t("roles.roles_url")
			when "groupapps"
				t("groupapps.groupapps_url")
			when "controllersdroits"
				t("controllersdroits.controllersdroits_url")
			when "statistics"
				t("statistics.statistics_url")
		end
	end

	def get_link_home(controller)
		"#{link_to(get_controller_language('presentations'), :controller=>"presentations")}/" unless controller == "presentations"
	end

	def set_params_for_link(params)
		detail_params = params.scan(/^(.{1,})=(.{1,})$/)[0]
		unless params.nil?
		      case detail_params[0].to_s
			    when "role_id"
				result_link = "#{set_params_roles(detail_params[1])}"
			    when "arrow"
				result_link = set_params_arrow(detail_params[1])
		      end 
		else
			result_link = "#{link_to t("applications.applications_url"), applications_path}"
		end
		result_link
	end

	def set_params_arrow(arrow_stat)
		unless arrow_stat.empty?
			case arrow_stat.to_s
				when "up"
					link_order_type = t("applications.arrow_up") 
				when "down"
					link_order_type = t("applications.arrow_down")

			end	
		else
			link_order_type = "#{link_to t("applications.applications_url"), application_path}"
		end
		link_order_type
	end

	def set_params_roles(role_id)
		unless role_id.empty?
			user_role_id = current_user.role_id
			role = Role.find(role_id)
			role_id_parent = role.role_id
			result_link = ""
			link_save = role.name
		      unless role_id_parent != user_role_id
			while (role_id_parent > user_role_id)
				role = Role.find(role_id_parent)
				result_link += "#{link_to role.name, :controller=>"applications", :action=>"index", :role_id=>role.id}/"		
				role_id_parent = role.role_id
			end
		      end
			result_link += link_save 	
		else
			result_link = "#{link_to t("applications.applications_url"), applications_path}"
		end
		result_link
	end	
end

app/helpers/applications_helper.rb
module ApplicationsHelper
	def get_size_tab_applications_apps
		#current_user.role_id == 1 ? 834 : 690
		taille_tableau = 834 
		taille_tableau -= 144 unless current_user.role_id == 1
		taille_tableau -= 89 unless @controller.control_acces_user_controller("pings","show")	
		taille_tableau
	end

	def get_roles_applications(role_id)
		roles = Role.find(:all, :conditions=>"role_id=#{role_id}")	

		unless roles.empty?
			result_ul_role = "<ol style='list-style-type:none;'>"
			roles.each do |role|
				result_ul_role += "<li>#{radio_button(:application, :role_id, role.id)}#{role.name}"
					unless get_roles_applications(role.id) == 0
						result_ul_role += get_roles_applications(role.id)
					end
				result_ul_role += "</li>"
			end
			result_ul_role += "</ol>"
			result_ul_role
		else
			0
		end
	end

	def url_controller_action_name_apps(controller_action_name)
		case controller_action_name
			when "new"
				"new.png"
			when "index"
				"state.png"
                        when "apps_sharing_zips"
				"folder.png"
                 end
		
	end

	def url_controller_action_name_apps_text(controller_action_name)
		case controller_action_name
			when "new"
				t("applications.new_license")
			when "index"
				t("applications.etat")
  			when "apps_sharing_zips"
				zip  = Fichiercompression.find(params[:id])
				"#{zip.description}"
		end
	end

	def set_parent_home_applications(user_role_id, params_role_id)
		tab_role = get_parent_home_applications(user_role_id, params_role_id)
		result_roles = ""
		liste_roles = ""
		0.upto(tab_role.length-1) { |i|
			roles = Role.find(:all, :conditions=>"role_id=#{tab_role[i]}")
			
			result_roles = "<ul style='list-style-type:none;line-height:22px;'>" 
			roles.each{ |role|
				if i > 0
					result_roles += "<li>#{link_to role.name.downcase, {:controller=>"applications", :action=>"index", :role_id=>role.id}, :style=>"color:black;#{params_role_id.to_i == role.id ? "text-decoration:underline;" : "text-decoration:none;" }"}"
						if tab_role[i-1].to_i == role.id.to_i
							result_roles += liste_roles
						end
					result_roles += "</li>"	
				else
					result_roles += "<li>#{link_to role.name.downcase, {:controller=>"applications", :action=>"index", :role_id=>role.id}, :style=>"color:black;#{params_role_id.to_i == role.id ? "text-decoration:underline;" : "text-decoration:none;" }"}</li>"
				end	
			}
			result_roles += "</ul>"
			liste_roles = result_roles
		}

		result_roles
	end

	private
	def get_parent_home_applications(user_role_id,params_role_id)
		tab_role = Array.new 
		tab_role.push(params_role_id)
		while user_role_id != params_role_id do 
			role = Role.find(params_role_id)
			tab_role.push(role.role_id)
			params_role_id = role.role_id
		end

		tab_role
	end
end

app/views/applications/_form.html.erb
	<div id='div_id_result_new_application' style='display:none;'>
	</div>
<div id='div_id_form_add_apps'>
  <div id='div_id_new_apps'>
	<ul id='ul_id_form_new_apps'>
  		<li <%= !flash[:notice].nil? ? "" : "style='color:#98CC54;font-weight:bold;'" %> >
			<div class='span_class_etape1'><%= t("applications.etape1") %></div>
  		</li>
  		<li class='class_etape_suivante'>
			<div class='span_class_etape'><%= t("applications.etape2") %></div>
		</li>
		<li class='class_etape_suivant'>
			<div class='span_class_etape'><%= t("applications.etape3") %></div>
		</li>
		<li <%= !flash[:notice].nil? ? "style='color:#98CC54;font-weight:bold;'" : "" %> class='class_etape_suivante_fin'>
			<div class='span_class_etape2'><%= t("applications.etape4") %></div>
		</li>
	</ul>
  </div>

<div class='form_detail_apps_edit'>
 <ul id='main'>
  <% if flash[:notice].nil? || flash[:applicationrecap].nil? %>
    <li id='etape1'>
    	<h3>1. <%= t("applications.define_licence_type") %></h3>
	<div class='div_class_height_contenu'>
		<%= f.select(:groupapp_id, Groupapp.find(:all, :conditions=>{:roles=>{:id=>current_user.role_id}}, :joins=>[:roles]).collect{|p| [p.name, p.id]}) %>
		<% 
			#link_to "Ajouter un nouveau type d'application", :controller=>"groupapps", :action=>"new" 
		%>
		<%=
			link_to(t("applications.add_new_type_apps"), {:controller=>"javascript", :action=>"add_new_groupapps"}, :class=>"class_link_add_type_apps") if @controller.control_acces_user_controller("groupapps","index") 
		%>
	</div>
	<div class='div_class_bouton_suivant'>
		<%= button_to_function t("header.next"), :name=>"buton_suivant", :class=>"class_buton_name_apps", :id=>"id_buton_next_1_to_2" %>
	</div>
    </li>

    <li id='etape2'>
    	<h3>2. <%= t("applications.choose_name_licence") %></h3> 
	<div class='div_class_height_contenu_etape2'>
		<%= render(:partial=>"/applications/templates/form_name_application", :locals => {:f => f}) %>
	      <p>
		<%= f.label(:role_id, t("activerecord.attributes.application.role_id")) %>
		<div class='div_class_choix_roles_apps'>
		       <ol>
			   <li>
				<%= radio_button(:application, :role_id, current_user.role_id) %> <%= current_user.role.name %>	
			   	<%= get_roles_applications(current_user.role_id) unless get_roles_applications(current_user.role_id) == 0 %>
			   </li>
		       </ol>
		</div>
	     </p>
	</div>


	<div class='div_class_bouton_suivant'>
		<%= button_to_function t("header.previous"), :name=>"buton_retour", :class=>"class_buton_name_apps", :id=>'id_buton_retour_2_to_1' %>
		<%= 
			#f.submit t("general.submit") 
		button_to_function t("header.next"), :name=>"buton_suivant", :class=>"class_buton_name_apps", :id=>"id_buton_next_2_to_3"
		%>
	</div>
   </li>
   <li id='etape3'>
   	<div class='div_class_height_contenu_etape3'>
		<%= t("applications.phrase_reception_facturation") %>
	</div>
	<div class='div_class_bouton_suivant'>
		<%= button_to_function t("header.previous"), :name=>"buton_retour", :class=>"class_buton_name_apps", :id=>"id_buton_retour_3_to_2" %><%= f.submit t("general.submit") %>
	</div>
   </li>
  <% else %>
  <li id='etape4'>
  	<h3>3. <%= flash[:notice] %></h3>
	<ol>
		<li>
			<%= t("applications.licence") %> : <%= @application_recap.id %>
		</li>

		<li>
			<%= t("applications.type") %> : <%= @application_recap.groupapp.name %>
		</li>
		<li>
			<%= t("applications.name") %> : <%= @application_recap.name %>
		</li>
		<li>
			<%= t("applications.serial") %> : <%= @application_recap.serial %>
		</li>
		<li>	
			<%= link_to "Retourner aux dispositifs", applications_url %>
		</li>
	</ol>	
  </li>
  <% end %>
 </ul>
</div>
</div>

app/views/applications/apps_sharing_zips.html.erb
<div class='class_title_appssharing_zips'><%= t("tab_zip.title_apps_appartenant_fichier") %> <%= link_to @zips.description, @zips.file.url %> <%= t("tab_zip.title_suite_apps_appartenant_fichier") %></div>
<div class='div_class_apps_file'>
<% form_for :applicationzips, :url=>{:controller=>"applications", :action=>"editapplicationszips"} do |f| %>
<%= f.hidden_field :zip_id, :value=>params[:id] %>
<table border='0' width='490' class='tab_class_apps_files' cellpadding='0' cellspacing='0'>
	<tr class='colonne_titre'>
		<td class='colonne_general_files_first' width='200'>
			<%= t("tab_app.nom_application") %>
		</td>

		<td class='colonne_general' width='90'>
			<%= t("tab_app.serial") %>
		</td>

		<td class='colonne_general' width='120'>
			<%= t("tab_app.editmultiple") %>
		</td>

                <td class='colonne_general_files_last'>
                        <%= image_tag("img_general/bin.png") %>
                </td>
	</tr>
	<% @zips.avoirs.find(:all).each{ |avoir| %>
		<tr class='class_contenu_colonne_user'>
			<td class='contenu_colonne_general'>
				<%= link_to image_tag("applications/plus.png", :size=>"20x20"), :controller=>"zips", :action=>"index", :id=>avoir.application.id %>
				<%= avoir.application.name %>
			</td>

			<td class='contenu_colonne_general'>
				<span class='class_align_right'><%= avoir.application.serial %></span>
			</td>

			<td class='contenu_colonne_general'>
				<%= check_box_tag("applicationzips[application_id][]", avoir.application.id, avoir.currentversion) %>
			</td>

                        <td class='contenu_colonne_general'>
                                <%= link_to image_tag("img_general/close.gif", :style=>'border:0px;', :class=>"class_img_link_sup_file"), {:controller=>"applications", :action=>"destroy_zip", :id=>avoir.application.id} %>
			</td>

		</tr>	
	<% } %>
</table>
	<%= 
		#f.submit t("tab_zip.bouton_sup_selection_apps"), :name=>"sup_apps_select", :confirm=>t("tab_zip.confirmation_sup_fichier_apps") 
	%>
	<%= f.submit "Editer", :name=>"fichiers_courants_apps" %>
<% end %>
</div>

app/views/applications/edit.html.erb
   <% form_for(@application) do |f| %> 
        <div style='text-align:center;'>
		<p>
		<%= render(:partial=>"/applications/templates/form_name_application", :locals => {:f => f}) %>
		</p>
		<%= f.submit("Mettre à jour") %>
        </div>
   <% end %>
<% 
	#link_to t("general.back"), :controller=>"applications", :action=>"index", :groupapp_id=>@application.groupapp_id 
%>

app/views/applications/edit_all.html.erb
<% form_for :application, @application, :url=>{:controller=>"application", :action=>"valid_update_all_application"} do |application| %>
	<% @application.each do |info_application| %>
		<div style='margin-top:40px;background-color:<%= @val == 1 ? "silver": "white" %>'>
		<strong><%= info_application.name %></strong>	
		<p>
		<% application.fields_for :info_application, info_application do |application_fields| %>
			<%= application_fields.label(:name, "Nom de l'application") %><br /> <%= application_fields.text_field :name, "index"=>info_application.id %>
		<% end %>
		   <ul>
			<% Role.all.collect{ |role| %>
				<li>
				<%= check_box_tag("application[info_application][#{info_application.id}][role_ids][]", role.id, info_application.roles.include?(role)) %> <%= label_tag(role.name) %>
				</li>
			<% } %>
		   </ul>
		</p>
		<% @val = (@val == 1 ? 0 : 1) %>
	<% end %>
	<%= application.submit "Modifier" %>
<% end %>

app/views/applications/edit_client.html.erb
<h1>Information sur le client</h1>
<% form_for :application_client, @application_client , :url=>{:controller=>"applications", :action=>"valid_edit_client"}, :html=>{:method=>:get} do |f| %>
  		<%= f.error_messages %>
		<p>
			<%= f.label(:serial) %> : <br>
			<%= f.text_field :serial %>
		</p>

		<p>
			Nom de l'utilisateur : <br>
			<%= text_field(:users, :username) %>
		</p>

		<p>
			Mot de passe : <br>
			<%= text_field(:users, :password) %>
		</p>

		<p>
		<%= f.label(:mac, "Adresse Mac") %> : <br>
		<%= f.text_field :mac %>
		</p>

		<%= f.submit "valider" %>
<% end %>

app/views/applications/edit_etat.html.erb
<h1>Etat de l'application</h1>
<% form_for :edit_etat_application, @application_edit_etat, :url=>{:controller=>"applications", :action=>"valid_edit_etat"}, :html=>{:method=>:get} do |f| %>
	<%= f.text_field :serial %>
	<p>
		<%= f.label(:enregistrement, "enregistrement") %>
		<%= f.check_box(:enregistrement) %>
	</p>

	<%= f.submit "Enregistrer" %>
<% end %>

app/views/applications/edit_select.html.erb
<% form_for :attribution_roles, :url=>{:controller=>"applications", :action=>"valid_attribution_role"} do |attribution_roles| %>
	<% 0.upto(@tab_application.length-1){ |i| %>	
		<%= hidden_field_tag("attribution_roles[application_id][]", @tab_application[i]) %>
	<% } %>


		<%= attribution_roles.label('Groupe : ') %>
      		<ul>
  			<% Role.all.collect{ |role| %>
				<li>
				<%= check_box_tag("attribution_roles[role_ids][]", role.id) %> <%= label_tag(role.name) %>
				</li>		
			<% } %>
		</ul>
		<%= attribution_roles.submit "valider" %>
<% end %>

app/views/applications/new.html.erb
<% form_for(@application) do |f| %>
	<%= render(:partial=>"/applications/templates/form", :locals => {:f => f}) %>
<% end %>

app/views/applications/search_auto_completion.js.erb
<%= auto_complete_result @application, :serial %>

app/views/applications/valid_edit_client.html.erb
fdqsfdsfsdfs